FROM python:3.10

WORKDIR /app

COPY app_sub.py /app/app.py
COPY subscriptions_functions.py /app/subscriptions_functions.py
COPY requirements_sub.txt /app/requirements.txt
COPY app /app/app


RUN pip install --no-cache-dir -r requirements.txt

CMD ["python", "app.py"]
